using System.ComponentModel.DataAnnotations;

namespace ReserveCenter.API.Models.Enums
{
    public enum CityEnum
    {
        [Display(Name = "همه")] All = 0,
        [Display(Name = "تهران")] Tehran = 1,
        [Display(Name = "شهریار")] Shahriar = 2,
        [Display(Name = "قدس")] Qods = 3,
        [Display(Name = "اسلامشهر")] Eslamshahr = 4,
        [Display(Name = "رباط‌کریم")] RobatKarim = 5,
        [Display(Name = "بهارستان")] Baharestan = 6,
        [Display(Name = "پاکدشت")] Pakdasht = 7,
        [Display(Name = "ورامین")] Varamin = 8,
        [Display(Name = "قرچک")] Qarchak = 9,
        [Display(Name = "دماوند")] Damavand = 10,
        [Display(Name = "فیروزکوه")] Firuzkuh = 11,
        [Display(Name = "پردیس")] Pardis = 12,
        [Display(Name = "اصفهان")] Isfahan = 13,
        [Display(Name = "کاشان")] Kashan = 14,
        [Display(Name = "نجف‌آباد")] NajafAbad = 15,
        [Display(Name = "خمینی‌شهر")] KhomeiniShahr = 16,
        [Display(Name = "شاهین‌شهر")] ShahinShahr = 17,
        [Display(Name = "فولادشهر")] Fooladshahr = 18,
        [Display(Name = "مبارکه")] Mobarakeh = 19,
        [Display(Name = "گلپایگان")] Golpayegan = 20,
        [Display(Name = "زرین‌شهر")] ZarrinShahr = 21,
        [Display(Name = "آران و بیدگل")] AranVaBidgol = 22,
        [Display(Name = "کرمان")] Kerman = 23,
        [Display(Name = "سیرجان")] Sirjan = 24,
        [Display(Name = "رفسنجان")] Rafsanjan = 25,
        [Display(Name = "جیرفت")] Jiroft = 26,
        [Display(Name = "بم")] Bam = 27,
        [Display(Name = "زرند")] Zarand = 28,
        [Display(Name = "کهنوج")] Kahnooj = 29,
        [Display(Name = "شهربابک")] ShahrBabak = 30,
        [Display(Name = "بافت")] Baft = 31,
        [Display(Name = "راور")] Ravar = 32,
        [Display(Name = "شیراز")] Shiraz = 33,
        [Display(Name = "مرودشت")] Marvdasht = 34,
        [Display(Name = "کازرون")] Kazeroon = 35,
        [Display(Name = "جهرم")] Jahrom = 36,
        [Display(Name = "فسا")] Fasa = 37,
        [Display(Name = "لار")] Lar = 38,
        [Display(Name = "داراب")] Darab = 39,
        [Display(Name = "فیروزآباد")] Firuzabad = 40,
        [Display(Name = "آباده")] Abadeh = 41,
        [Display(Name = "اقلید")] Eqlid = 42
    }
}
